version: '3.8'

services:

  rps_api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    environment:
      WEB_APP_HOST: "0.0.0.0"
      WEB_APP_PORT: "5000"
      DEBUG: "False"
    ports:
      - 5000:5000
