ROCK = "rock"
ROCK_INDEX = 0
ROCK_REWARD_LIST = [-1, 1, -2]

PAPER = "paper"
PAPER_INDEX = 1
PAPER_REWARD_LIST = [-2, -1, 1]

SCISSORS = "scissors"
SCISSORS_INDEX = 2
SCISSORS_REWARD_LIST = [1, -2, -1]

GAME_TIE = "tie"
GAME_WIN = "win"
GAME_LOOSE = "loose"
